# Generated by Django 4.0.2 on 2024-12-10 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marka', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='images/')),
                ('comments', models.TextField()),
                ('year', models.IntegerField()),
                ('color', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('phone', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'News', 'verbose_name_plural': 'News'},
        ),
    ]
