# Generated by Django 4.0.2 on 2024-12-24 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('model', models.CharField(max_length=50)),
                ('ram', models.IntegerField(default=0)),
                ('storage', models.IntegerField(default=0)),
                ('cpu', models.CharField(max_length=50)),
                ('price', models.IntegerField(default=0)),
            ],
        ),
    ]
